<?php

/**
 * BaseGeolocatableArticle_CityStateZip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $city
 * @property string $state
 * @property string $zip
 * 
 * @method string                           getName()  Returns the current record's "name" value
 * @method string                           getCity()  Returns the current record's "city" value
 * @method string                           getState() Returns the current record's "state" value
 * @method string                           getZip()   Returns the current record's "zip" value
 * @method GeolocatableArticle_CityStateZip setName()  Sets the current record's "name" value
 * @method GeolocatableArticle_CityStateZip setCity()  Sets the current record's "city" value
 * @method GeolocatableArticle_CityStateZip setState() Sets the current record's "state" value
 * @method GeolocatableArticle_CityStateZip setZip()   Sets the current record's "zip" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGeolocatableArticle_CityStateZip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('geolocatable_article__city_state_zip');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('state', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('zip', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $geolocatable0 = new Doctrine_Template_Geolocatable(array(
             'fields' => 
             array(
              0 => 'city',
              1 => 'state',
              2 => 'zip',
             ),
             ));
        $this->actAs($geolocatable0);
    }
}