<?php

/**
 * BaseGeolocatableArticle_Address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $address
 * 
 * @method string                      getName()    Returns the current record's "name" value
 * @method string                      getAddress() Returns the current record's "address" value
 * @method GeolocatableArticle_Address setName()    Sets the current record's "name" value
 * @method GeolocatableArticle_Address setAddress() Sets the current record's "address" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGeolocatableArticle_Address extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('geolocatable_article__address');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $geolocatable0 = new Doctrine_Template_Geolocatable(array(
             'fields' => 
             array(
              0 => 'address',
             ),
             ));
        $this->actAs($geolocatable0);
    }
}